[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "astromcad"
authors = [{name = "Rithwik", email = "rithwikca2020@gmail.com"}]
dynamic = ["version", "description"]
